name: CI Angular devops

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name : adding angular envirement action
      uses: actions/angular-github-actions@latest
    - run : npm install 
    - run : ng serve 
